# Generated by Django 5.1.5 on 2025-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichat',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
