# Generated by Django 5.1.5 on 2025-01-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_chat', '0002_alter_aichat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichat',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
