# Generated by Django 5.1.5 on 2025-01-20 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.CharField(max_length=255, null=True)),
                ('user_question', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('total_tokens', models.CharField(default=256, max_length=255, null=True)),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('CONTINUE', 'Continue'), ('IMPROVE', 'Improve'), ('SHORTER', 'Shorter'), ('LONGER', 'Longer'), ('FIX', 'Fix'), ('ZAP', 'Zap'), ('INSTRUCTION', 'Instruction'), ('CHART', 'Chart')], default='INSTRUCTION', max_length=50)),
            ],
        ),
    ]
